Update nova logging.conf to reflect changes in nova trunk.
The "LegacyFormatter" was recently removed from nova in this
change:  3e136dea2b259def305c9032cab5e1a08243c1c6.

As a result, the nova logging.conf template in this repo contained
an undefined reference to nova.openstack.common.log.LegacyFormatter,
causing nova services to fail to start.

This change replaces LegacyFormatter with ContextFormatter.

Change-Id: I9ef9610e2707dc2a9966c777172e365cc75fbb97